---
- name: "upgrade packages."
  become: true
  ansible.builtin.apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  ansible.builtin.apt:
    name: ["nodejs", "npm"] # do I also need python?!
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  community.general.npm:
    name: pm2
    global: yes
    production: yes
    state: present
