---
- name: "set environment variables"
  ansible.builtin.shell: |
    echo "# Custom environment variables" >> /home/ubuntu/.profile

    echo "export TYPEORM_CONNECTION=${TYPEORM_CONNECTION}" >> /home/ubuntu/.profile
    echo "export TYPEORM_ENTITIES=${TYPEORM_ENTITIES}" >> /home/ubuntu/.profile
    echo "export TYPEORM_HOST=${TYPEORM_HOST}" >> /home/ubuntu/.profile
    echo "export TYPEORM_PORT=${TYPEORM_PORT}" >> /home/ubuntu/.profile

    echo "export TYPEORM_USERNAME=${TYPEORM_USERNAME}" >> /home/ubuntu/.profile
    echo "export TYPEORM_PASSWORD=${TYPEORM_PASSWORD}" >> /home/ubuntu/.profile
    echo "export TYPEORM_DATABASE=${TYPEORM_DATABASE}" >> /home/ubuntu/.profile
    echo "export TYPEORM_MIGRATIONS=${TYPEORM_MIGRATIONS}" >> /home/ubuntu/.profile
    echo "export TYPEORM_MIGRATIONS_DIR=${TYPEORM_MIGRATIONS_DIR}" >> /home/ubuntu/.profile

- name: "upgrade packages."
  become: true
  ansible.builtin.apt:
    upgrade: "yes"

- name: "install dependencies."
  become: true
  ansible.builtin.apt:
    name: ["nodejs", "npm"] # do I also need python?!
    state: latest
    update_cache: yes

- name: "install pm2"
  become: true
  community.general.npm:
    name: pm2
    global: yes
    production: yes
    state: present
