---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html
# - name: "copy tar archive"
#   ansible.builtin.copy:
#     src: ../../artifact.tar.gz
#     dest: ~/artifact.tar.gz
#     owner: root
#     group: root
#     mode: "0777"

- name: "create dir for backend"
  ansible.builtin.shell: |
    mkdir -p ~/backend

- name: "copy and unpack archive"
  ansible.builtin.unarchive:
    src: ../../artifact.tar.gz
    dest: ~/backend
    remote_src: no

- name: "start pm2"
  ansible.builtin.shell: |
    cd ~/backend
    npm install
    pm2 stop default
    pm2 --update-env start npm -- start
